title:              인천대학교 건설경영및관리 연구실
email:              taewkim@inu.ac.kr #김태완 교수님 이메일
description:        
author:             INUCEM
baseurl:            ""
url:                "https://inucem.github.io"

# Social Profiles
twitter_username:
github_username:    INUCEM
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
